sudo: false

language: php

cache:
  directories:
    - vendor

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env:
        - EXECUTE_DOC_CHECK=true
    - php: 5.6
      env:
        - EXECUTE_CS_CHECK=true
    - php: 7
    - php: hhvm
  allow_failures:
    - php: 7
    - php: hhvm


before_install:
  - composer self-update
  - if [[ $EXECUTE_DOC_CHECK == 'true' ]]; then composer require --dev --no-update; fi

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs --prefer-source
  - composer info -i

script:
# - (cd test ; ../vendor/bin/phpunit -c phpunit.xml)
 - ./vendor/bin/php-cs-fixer -v fix . --dry-run --config-file ./.php_cs
